---
- name: Bureaublad en Verkenner Finetuning
  hosts: localhost
  connection: local
  tasks:
    - name: Installeer Nemo extra's en Disk Utility
      become: yes
      apt:
        name:
          - gnome-disk-utility
          - dconf-editor
          - nemo-fileroller
        state: present
        update_cache: yes
      ignore_errors: yes

    - name: Configureer Desktop Iconen (Windows Stijl)
      shell: |
        gsettings set org.nemo.desktop computer-icon-visible true || true
        gsettings set org.nemo.desktop home-icon-visible true || true
        gsettings set org.nemo.desktop trash-icon-visible true || true
        gsettings set org.nemo.desktop volumes-visible true || true
      args:
        executable: /bin/bash

    - name: Optimaliseer Nemo (Verkenner)
      shell: |
        gsettings set org.nemo.preferences show-pathbar-buttons false || true
        gsettings set org.nemo.preferences always-use-browser true || true
      args:
        executable: /bin/bash
