---
- name: Remote Support Tools Installatie (TeamViewer & RustDesk)
  hosts: localhost
  connection: local
  vars:
    real_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
  tasks:
    - name: Installeer curl
      become: yes
      apt:
        name: curl
        state: present

    - name: Download en Installeer TeamViewer
      become: yes
      apt:
        deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
        state: present
      ignore_errors: yes

    - name: Haal RustDesk URL op en Installeer
      become: yes
      shell: |
        URL=$(curl -s https://api.github.com/repos/rustdesk/rustdesk/releases/latest | grep "browser_download_url.*amd64.deb" | cut -d '"' -f 4)
        wget -O /tmp/rustdesk.deb $URL
        apt install -y /tmp/rustdesk.deb
      ignore_errors: yes

    - name: Snelkoppelingen op het echte bureaublad
      become: yes
      shell: |
        DESKTOP_DIR="/home/{{ real_user }}/Desktop"
        [ ! -d "$DESKTOP_DIR" ] && DESKTOP_DIR="/home/{{ real_user }}/Bureaublad"
        
        cp /usr/share/applications/com.teamviewer.TeamViewer.desktop "$DESKTOP_DIR/" || true
        cp /usr/share/applications/rustdesk.desktop "$DESKTOP_DIR/" || true
        
        chown -R {{ real_user }}:{{ real_user }} "$DESKTOP_DIR"
        chmod +x "$DESKTOP_DIR"/*.desktop
      args:
        executable: /bin/bash
      ignore_errors: yes
