---
- name: Activeer achtergrondrotatie
  hosts: localhost
  connection: local
  tasks:
    - name: Forceer aanmaak van de map wallpapers
      file:
        path: "/home/henry/Afbeeldingen/wallpapers"
        state: directory
        mode: '0755'

    - name: Link de bestanden (Forceer met shell)
      shell: |
        mkdir -p /home/henry/Afbeeldingen/wallpapers
        ln -sf /usr/share/backgrounds/debian/* /home/henry/Afbeeldingen/wallpapers/
        ln -sf /usr/share/backgrounds/gnome/* /home/henry/Afbeeldingen/wallpapers/
      args:
        executable: /bin/bash

    - name: Controleer of de map nu echt bestaat
      stat:
        path: "/home/henry/Afbeeldingen/wallpapers"
      register: folder_check

    - name: Stop als de map niet is aangemaakt
      fail:
        msg: "De map /home/henry/Afbeeldingen/wallpapers is nog steeds niet gevonden!"
      when: not folder_check.stat.exists
